// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_keeping_it_safe = "CgkI2Kzvmb4GEAIQFA"; // <GPGSID>
        public const string achievement_old_man = "CgkI2Kzvmb4GEAIQDQ"; // <GPGSID>
        public const string achievement_coin_collector = "CgkI2Kzvmb4GEAIQEQ"; // <GPGSID>
        public const string achievement_coin_dodger = "CgkI2Kzvmb4GEAIQFg"; // <GPGSID>
        public const string achievement_im_fancy = "CgkI2Kzvmb4GEAIQEA"; // <GPGSID>
        public const string achievement_prince = "CgkI2Kzvmb4GEAIQBw"; // <GPGSID>
        public const string achievement_learn_the_basics = "CgkI2Kzvmb4GEAIQBA"; // <GPGSID>
        public const string achievement_king = "CgkI2Kzvmb4GEAIQCQ"; // <GPGSID>
        public const string achievement_at_least_its_an_achivement = "CgkI2Kzvmb4GEAIQFQ"; // <GPGSID>
        public const string achievement_king_of_jumps = "CgkI2Kzvmb4GEAIQEw"; // <GPGSID>
        public const string achievement_seen_the_worst = "CgkI2Kzvmb4GEAIQDw"; // <GPGSID>
        public const string achievement_loyal_man = "CgkI2Kzvmb4GEAIQDg"; // <GPGSID>
        public const string achievement_hyper_hopper = "CgkI2Kzvmb4GEAIQBQ"; // <GPGSID>
        public const string achievement_begginer = "CgkI2Kzvmb4GEAIQAw"; // <GPGSID>
        public const string achievement_its_actually_easier = "CgkI2Kzvmb4GEAIQCA"; // <GPGSID>
        public const string achievement_master = "CgkI2Kzvmb4GEAIQCw"; // <GPGSID>
        public const string achievement_best_out_there = "CgkI2Kzvmb4GEAIQDA"; // <GPGSID>
        public const string achievement_jump_expert = "CgkI2Kzvmb4GEAIQEg"; // <GPGSID>
        public const string achievement_legend = "CgkI2Kzvmb4GEAIQCg"; // <GPGSID>
        public const string achievement_survivor = "CgkI2Kzvmb4GEAIQBg"; // <GPGSID>
        public const string leaderboard_best_score = "CgkI2Kzvmb4GEAIQAQ"; // <GPGSID>

}

